import SphereCover from './SphereCover'
import ExternalLinkArrow from './ExternalLinkArrow'
import {
  BodyText,
  SectionLabel,
  SectionTitle,
} from './case-study/CaseStudyPrimitives'
import './NokiaCaseStudy.css'

const TREND_TAGS = [
  'Self care and prevention',
  'Digital solutions and virtual care',
  'Big data to understand the patient',
]

const SURVEY_STATS = [
  {
    value: '83%',
    text: 'believes mood monitoring apps don’t provide real solutions.',
  },
  {
    value: '90%',
    text: 'would like to make better use of their free time for new activities.',
  },
  {
    value: '69%',
    text: 'acknowleged they often lack awareness of their mental state.',
  },
  {
    value: '71%',
    text: 'has trouble organizing their time and schedule.',
  },
]

const PERSONAS = [
  {
    role: 'The workaholic',
    name: 'Vicente',
    image: '/work/sphere/persona-workaholic.png',
    bio: [
      'I love my job, I focus 100% on it.',
      "I don't understand why if I'm doing something I love, I don't feel happy.",
    ],
  },
  {
    role: 'The FOMO',
    name: 'Marta',
    image: '/work/sphere/persona-fomo.png',
    bio: [
      "I'm a Journalist so I don't have a regular work schedule. I find it hard to order my life in order to see my friends and enjoy the day.",
    ],
  },
  {
    role: 'The analytical',
    name: 'Emilia',
    image: '/work/sphere/persona-analytical.png',
    bio: [
      'Since moving to a new city, my emotions have been all over the place. Understanding my patterns helps me feel more in control.',
    ],
  },
]

const USP_ITEMS = [
  {
    title: 'Mood tracking',
    text: 'You can visualize and control the devices that are in operation. So you can see what is happening in real time whether you are inside or outside the house.',
  },
  {
    title: 'Suggestion of activities',
    text: 'Our algorithm and ML provides the user with personalized recommendations for activities based on their mood, personal taste and past experiences.',
  },
  {
    title: 'Planner',
    text: 'A planner that helps people to structure and make better use of their free time; This planner can be synchronized with any calendar application.',
  },
  {
    title: 'Connect with friends',
    text: 'Because socializing plays a big role on ones well-being. A community where the user can share plans and feelings with friends.',
  },
]

const KPI_TAGS_ROW_1 = [
  'App downloads',
  'Active users',
  'How many users check-in',
  'Feedback given',
  'Booking of suggested activities',
]

const KPI_TAGS_ROW_2 = [
  'Revenues (generated by the activity’s commision)',
  'Percentage of users with each emotion',
  'Target: Achieve 30% of users as subscribers',
]

const BUSINESS_PLANS = [
  {
    title: 'Free',
    text: 'You have access to almost all the functions of the app (mood track, activity suggestions, insights).',
  },
  {
    title: 'Growth',
    price: '14€ / month ',
    text: 'All the benefits of the free plan + community access. In addition, it allows you to attend 5 paid classes or events per month.',
  },
]

const KEY_PARTNERS = [
  {
    title: 'Local businesses',
    detail: '200€ month',
  },
  {
    title: 'Other businesses',
    detail: '15% sales commission',
  },
]

const GO_TO_MARKET_ITEMS = [
  'Social media posts',
  'Landing page',
  'Stickers and posters in places',
]

function StatCard({ value, text }: { value: string; text: string }) {
  return (
    <div className="nokia-case__stat-card">
      <p className="nokia-case__stat-value">{value}</p>
      <p className="nokia-case__body">{text}</p>
    </div>
  )
}

export default function SphereCaseStudy() {
  return (
    <article className="nokia-case">
      <div id="sphere-intro">
        <div className="nokia-case__hero-group">
          <div className="nokia-case__intro">
            <h1 className="nokia-case__headline font-bricolage">
              Supporting Mental Wellbeing Through Everyday Habits
            </h1>

            <div className="nokia-case__meta">
              <div className="nokia-case__meta-row">
                <div className="nokia-case__meta-item">
                  <SectionLabel>Type</SectionLabel>
                  <p className="nokia-case__meta-value">Course work</p>
                </div>
                <div className="nokia-case__meta-item">
                  <SectionLabel>Date</SectionLabel>
                  <p className="nokia-case__meta-value">2023</p>
                </div>
              </div>

              <div className="nokia-case__meta-block nokia-case__meta-block--overview">
                <SectionLabel>Overview</SectionLabel>
                <BodyText>
                  This project was developed in the context of the Master of
                  Design and Management of User Experience and Digital Services
                  at ELISAVA.
                </BodyText>
              </div>
            </div>
          </div>

          <div className="nokia-case__cover">
            <SphereCover />
          </div>
        </div>
      </div>

      <section
        id="sphere-discovery"
        className="nokia-case__section nokia-case__section--spacious"
      >
        <div className="nokia-case__section-intro">
          <SectionLabel>Discovery</SectionLabel>
          <h2 className="nokia-case__subtitle">Problem space</h2>
          <BodyText>
            Mental health has become an increasingly present concern in our
            society. Nowadays, we are extremely busy: job, kids, house chores,
            late meetings, overtime. Time and energy doesn&apos;t stretch long
            enough to do everything which leads to neglect of leisure and
            self-care and, sooner than later, stress and anxiety eventually kick
            in.
          </BodyText>
        </div>
      </section>

      <section
        id="sphere-trends"
        className="nokia-case__section nokia-case__section--benchmark"
      >
        <div className="nokia-case__section-intro">
          <h2 className="nokia-case__subtitle">
            Trends in 2023 in the field of health
          </h2>
          <BodyText>
            We did a trend analyzis in order to find valuable, up-to-date
            information to provide our users with the best support, making our
            service more ettective and attractive.
          </BodyText>
        </div>

        <div className="nokia-case__tags nokia-case__tags--pills">
          {TREND_TAGS.map((tag) => (
            <span key={tag} className="nokia-case__tag nokia-case__tag--pill">
              {tag}
            </span>
          ))}
        </div>
      </section>

      <section
        id="sphere-surveys"
        className="nokia-case__section nokia-case__section--benchmark"
      >
        <div className="nokia-case__section-intro">
          <h2 className="nokia-case__subtitle">Surveys</h2>
          <BodyText>
            We surveyed 40 people about their habits, their time management and
            how these affected their mood. We also gained insights on how people
            are using mood monitoring apps and what were their main pains and
            needs.
          </BodyText>
        </div>

        <div className="nokia-case__stat-grid">
          {SURVEY_STATS.map((stat) => (
            <StatCard key={stat.value} value={stat.value} text={stat.text} />
          ))}
        </div>
      </section>

      <section id="sphere-challenge" className="nokia-case__section">
        <SectionLabel>Challenge</SectionLabel>
        <SectionTitle size="lg">
          How can we help people with poor emotion and time management to
          improve their well-being?
        </SectionTitle>
      </section>

      <section
        id="sphere-personas"
        className="nokia-case__section nokia-case__section--personas"
      >
        <div className="nokia-case__section-intro">
          <SectionLabel>Define</SectionLabel>
          <h2 className="nokia-case__subtitle">User personas</h2>
        </div>
        <div className="nokia-case__personas">
          <div className="nokia-case__persona-grid nokia-case__persona-grid--three">
            {PERSONAS.map((persona) => (
              <div key={persona.name} className="nokia-case__persona-card">
                <div className="nokia-case__persona-header">
                  <div className="nokia-case__persona-avatar nokia-case__persona-avatar--sphere">
                    <img src={persona.image} alt="" />
                  </div>
                  <div className="nokia-case__persona-meta">
                    <p className="nokia-case__persona-role">{persona.role}</p>
                    <p className="nokia-case__persona-name">{persona.name}</p>
                  </div>
                </div>
                <div className="nokia-case__persona-bio nokia-case__persona-bio--italic">
                  {persona.bio.map((line) => (
                    <p key={line}>{line}</p>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section
        id="sphere-user-journeys"
        className="nokia-case__section nokia-case__section--wireframes"
      >
        <div className="nokia-case__section-intro">
          <h2 className="nokia-case__subtitle">User journeys</h2>
          <BodyText>
            We wanted to discover the users&apos; pain points in order to
            understant when and how we needed to act.
          </BodyText>
        </div>
        <img
          src="/work/sphere/user-journeys.png"
          alt=""
          className="nokia-case__wireframes-image"
        />
      </section>

      <section
        id="sphere-usps"
        className="nokia-case__section nokia-case__section--wireframes"
      >
        <div className="nokia-case__section-intro">
          <SectionLabel>USPs</SectionLabel>
          <h2 className="nokia-case__subtitle">Key functionalitites</h2>
        </div>

        <div className="nokia-case__usp-grid">
          {USP_ITEMS.map((item) => (
            <div key={item.title} className="nokia-case__usp-item">
              <p className="nokia-case__usp-title">{item.title}</p>
              <p className="nokia-case__body">{item.text}</p>
            </div>
          ))}
        </div>
      </section>

      <section
        id="sphere-kpis"
        className="nokia-case__section nokia-case__section--benchmark"
      >
        <div className="nokia-case__section-intro">
          <SectionLabel>Business strategy</SectionLabel>
          <h2 className="nokia-case__subtitle">KPIS</h2>
        </div>

        <div className="nokia-case__tag-rows">
          <div className="nokia-case__tags nokia-case__tags--pills">
            {KPI_TAGS_ROW_1.map((tag) => (
              <span key={tag} className="nokia-case__tag nokia-case__tag--pill">
                {tag}
              </span>
            ))}
          </div>
          <div className="nokia-case__tags nokia-case__tags--pills">
            {KPI_TAGS_ROW_2.map((tag) => (
              <span
                key={tag}
                className={`nokia-case__tag nokia-case__tag--pill${tag.startsWith('Target:') ? ' nokia-case__tag--bold' : ''}`}
              >
                {tag}
              </span>
            ))}
          </div>
        </div>
      </section>

      <section
        id="sphere-business-plan"
        className="nokia-case__section nokia-case__section--business-plan"
      >
        <h2 className="nokia-case__subtitle">Business plan</h2>

        <div className="nokia-case__business-plan">
          <div className="nokia-case__plan-cards nokia-case__plan-cards--row">
            {BUSINESS_PLANS.map((plan) => (
              <div key={plan.title} className="nokia-case__plan-card">
                {plan.price ? (
                  <div className="nokia-case__plan-header">
                    <p className="nokia-case__plan-title font-bricolage">
                      {plan.title}
                    </p>
                    <p className="nokia-case__plan-price font-bricolage">
                      {plan.price}
                    </p>
                  </div>
                ) : (
                  <p className="nokia-case__plan-title font-bricolage">
                    {plan.title}
                  </p>
                )}
                <p className="nokia-case__body">{plan.text}</p>
              </div>
            ))}
          </div>

          <div className="nokia-case__key-partners">
            <p className="nokia-case__body nokia-case__key-partners-label">
              Our key partners:
            </p>
            <div className="nokia-case__key-partners-row">
              {KEY_PARTNERS.map((partner) => (
                <div key={partner.title} className="nokia-case__key-partner">
                  <p className="nokia-case__key-partner-title">{partner.title}</p>
                  <p className="nokia-case__key-partner-detail">{partner.detail}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="nokia-case__go-to-market">
          <div className="nokia-case__section-intro">
            <h3 className="nokia-case__gtm-title font-bricolage">
              Go to market strategy
            </h3>
            <BodyText>
              To launch the app, we will run an awareness campaign on social
              media. We will also publish a landing page with all the details
              about the app and place stickers at all of the app&apos;s partner
              businesses.
            </BodyText>
          </div>
          <div className="nokia-case__tags">
            {GO_TO_MARKET_ITEMS.map((item) => (
              <span key={item} className="nokia-case__tag">
                {item}
              </span>
            ))}
          </div>
        </div>
      </section>

      <section id="sphere-app-overview" className="nokia-case__section">
        <div className="nokia-case__section-intro">
          <SectionLabel>Ideation</SectionLabel>
          <h2 className="nokia-case__subtitle">App overview</h2>
        </div>
        <img
          src="/work/sphere/app-overview-grid.png"
          alt=""
          width={1372}
          height={447}
          className="nokia-case__wireframes-image"
        />
      </section>

      <section id="sphere-thanks" className="nokia-case__section">
        <SectionTitle size="lg">Thank you!</SectionTitle>
        <a
          href="https://www.figma.com/proto/4olwG3O8T3bL4AjYyEi6gk/Sphere-Project---meu?page-id=1991%3A24&type=design&node-id=2591-1282&viewport=-81%2C2993%2C0.22&t=svPkAioki9mZl6Tn-1&scaling=scale-down&desktop-link-click-timestamp=1784503241555&desktop-ul-exp-bucket=po&desktop-ul-pref-conflict=1"
          className="nokia-case__nav-link"
          target="_blank"
          rel="noopener noreferrer"
        >
          <ExternalLinkArrow />
          Link to the prototype
        </a>
      </section>
    </article>
  )
}
